services:
  # FastAPI Service
  - type: web
    name: pump-anomaly-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.prediction:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: STORAGE_TYPE
        value: s3
      - key: S3_BUCKET
        value: anomaly-detection010
      - key: AWS_ACCESS_KEY_ID
        sync: false  # Set in Render dashboard for security
      - key: AWS_SECRET_ACCESS_KEY
        sync: false  # Set in Render dashboard for security
      - key: SECRET_KEY
        sync: false  # Set in Render dashboard for security
      - key: API_KEY
        sync: false  # Set in Render dashboard for security

  # Streamlit Dashboard Service
  - type: web
    name: pump-anomaly-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/dashboard.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: ENVIRONMENT
        value: production
      - key: API_URL
        value: https://pump-anomaly-api.onrender.com  # This will be the URL of your FastAPI service
      - key: API_KEY
        sync: false  # Will be set manually in Render dashboard
